version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-app
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - aserraquo-network

networks:
  aserraquo-network:
    external: true